server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/truewarehouse?serverTimezone=GMT%2B8
    username: root
    password: 'Taylor.swift1989'
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mapper/*.xml
